import { Poppins } from "@/resources/fonts";
import NextProvider from "../NextUIProvider";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Poppins.className}>
        <NextProvider>
          <main className="light text-foreground m-0 p-0 bg-background w-screen overflow-hidden min-h-screen font-poppins">
            {children}
          </main>
        </NextProvider>
      </body>
    </html>
  );
}
